class LoginLocators:
    LOGO = ".orangehrm-login-branding"
    SIDE_LOGO = "//*[@id='app']/div[1]/div/div[2]"
    PAGE_TITLE = ".oxd-text.oxd-text--h5.orangehrm-login-title"
    LOGIN_CREDS = ".orangehrm-login-error"
    INPUT_USERNAME = "[name='username']"
    INPUT_PASSWORD = "[name='password']"
    SUBMIT = "button[type='submit']"
    FORGOT_BUTTON = ".orangehrm-login-forgot-header"
    FOOTER_OS = ".orangehrm-copyright-wrapper p:first-of-type"
    FOOTER_LICENSE = ".orangehrm-copyright-wrapper p:last-of-type"
    FOOTER_LINK = ".orangehrm-copyright-wrapper a"
    LINKEDIN_LINK = "a[href*='linkedin.com']"
    FACEBOOK_LINK = "a[href*='facebook.com']"
    TWITTER_LINK = "a[href*='twitter.com']"
    YOUTUBE_LINK = "a[href*='youtube.com']"
    ERROR = ".oxd-alert.oxd-alert--error"
