import enum

BASE = "https://opensource-demo.orangehrmlive.com/web/index.php"
class URLS(enum.StrEnum):
    LOGIN = f"{BASE}/auth/login"
    MAIN_PAGE = "https://www.orangehrm.com/"
    LOGIN = "web/index.php/auth/login"
    ADMIN = "web/index.php/admin/viewSystemUsers"
    PIM = "web/index.php/pim/viewEmployeeList"
    LEAVE = "web/index.php/leave/viewLeaveList"
    TIME = "web/index.php/time/viewEmployeeTimesheet"
    RECRUITMENT = "web/index.php/recruitment/viewCandidates"
    MY_INFO = "web/index.php/pim/viewPersonalDetails/empNumber/7"
    PERFORMANCE = "web/index.php/performance/searchEvaluatePerformanceReview"
    DASHBOARD = "web/index.php/dashboard/index"
    ASSIGN_LEAVE = "web/index.php/leave/assignLeave"
    DIRECTORY = "web/index.php/directory/viewDirectory"
    MAINTENANCE = "web/index.php/maintenance/purgeEmployee"
    CLAIM = "web/index.php/claim/viewAssignClaim"
    BUZZ = "web/index.php/buzz/viewBuzz"
    APPLY_LEAVE = "web/index.php/leave/applyLeave"
    MY_LEAVE_LIST = "web/index.php/leave/viewMyLeaveList"
    MY_TIME_TIMESHEET = "web/index.php/time/viewMyTimesheet"
    SUPPORT = "web/index.php/help/support"
    CHANGE_PASSWORD = "web/index.php/pim/updatePassword"
    UPGRADE = "https://orangehrm.com/open-source/upgrade-to-advanced"
