class SidebarLocators:
    BANNER = ".oxd-brand-banner"
    SEARCH = "input[placeholder='Search']"
    SIDEBAR_TOGGLE = "button.oxd-icon-button.oxd-main-menu-button"
    ADMIN = "aside a[href*='viewAdminModule']"
    PIM = "aside a[href*='viewPimModule']"
    LEAVE = "aside a[href*='viewLeaveModule']"
    TIME = "aside a[href*='viewTimeModule']"
    RECRUITMENT = "aside a[href*='viewRecruitmentModule']"
    MY_INFO = "aside a[href*='viewMyDetails']"
    PERFORMANCE = "aside a[href*='viewPerformanceModule']"
    DASHBOARD = "aside a[href*='dashboard']"
    DIRECTORY = "aside a[href*='viewDirectory']"
    MAINTENANCE = "aside a[href*='viewMaintenanceModule']"
    CLAIM = "aside a[href*='viewClaimModule']"
    BUZZ = "aside a[href*='viewBuzz']"
